export const MOCK_COMPANIES = [
  { id: 1, name: "هيئة أبوظبي للصحة", primaryColor: "#C9A84C", secondaryColor: "#0a0a0f", plan: "Enterprise", jobs: 3, applicants: 47, hrUsers: 2 },
  { id: 2, name: "مجموعة أبوظبي للطاقة", primaryColor: "#2563eb", secondaryColor: "#0f172a", plan: "Professional", jobs: 2, applicants: 31, hrUsers: 1 },
  { id: 3, name: "دائرة التعليم والمعرفة", primaryColor: "#059669", secondaryColor: "#064e3b", plan: "Basic", jobs: 1, applicants: 19, hrUsers: 1 },
];

export const MOCK_APPLICANTS = [
  {
    id: 1,
    name: "أحمد محمد المنصوري",
    nationality: "إماراتي",
    phone: "+971 50 123 4567",
    email: "ahmed@email.com",
    location: "أبوظبي",
    currentTitle: "مهندس أول",
    experience: "10+ سنوات",
    lastEmployer: "هيئة أبوظبي للغذاء",
    education: "ماجستير إدارة التقنية",
    university: "جامعة زايد",
    gpa: "3.04",
    skills: ["إدارة مشاريع", "Excel", "إدارة مخاطر"],
    languages: ["عربي (لغة أم)", "إنجليزي (محترف)"],
    certifications: ["PMP", "ISO 26000", "IOSH"],
    aiSummary: "مرشح قوي بخبرة واسعة في إدارة المشاريع الحكومية. يمتلك مهارات تقنية وإدارية متميزة مع شهادات دولية معتمدة. يُنصح بالتقدم لمقابلة.",
    status: "مراجعة",
    rating: 5,
    date: "2025-04-24",
    companyId: 1,
    interviewDate: null,
    interviewTime: null,
    interviewNotes: "",
  },
  {
    id: 2,
    name: "فاطمة سعيد الكعبي",
    nationality: "إماراتية",
    phone: "+971 55 234 5678",
    email: "fatima@email.com",
    location: "دبي",
    currentTitle: "محاسبة قانونية",
    experience: "7 سنوات",
    lastEmployer: "بنك الإمارات الدولي",
    education: "بكالوريوس محاسبة",
    university: "جامعة الشارقة",
    gpa: "3.7",
    skills: ["محاسبة", "SAP", "تدقيق مالي"],
    languages: ["عربي (لغة أم)", "إنجليزي (متقدم)"],
    certifications: ["CPA", "ACCA"],
    aiSummary: "كفاءة مالية عالية مع خبرة في البيئات المصرفية. مناسبة جداً للأدوار المالية القيادية.",
    status: "مقبول",
    rating: 4,
    date: "2025-04-23",
    companyId: 1,
    interviewDate: "2025-05-10",
    interviewTime: "10:00",
    interviewNotes: "مقابلة مع مدير الموارد البشرية",
  },
  {
    id: 3,
    name: "خالد عبدالله الشامسي",
    nationality: "إماراتي",
    phone: "+971 52 345 6789",
    email: "khalid@email.com",
    location: "الشارقة",
    currentTitle: "مطور برمجيات أول",
    experience: "5 سنوات",
    lastEmployer: "اتصالات",
    education: "بكالوريوس علوم حاسوب",
    university: "جامعة خليفة",
    gpa: "3.2",
    skills: ["Python", "React", "AWS"],
    languages: ["عربي (لغة أم)", "إنجليزي (محترف)"],
    certifications: ["AWS Solutions Architect"],
    aiSummary: "مطور متكامل بخبرة في الحوسبة السحابية. مناسب للمناصب التقنية الرقمية.",
    status: "مراجعة",
    rating: 3,
    date: "2025-04-22",
    companyId: 1,
    interviewDate: null,
    interviewTime: null,
    interviewNotes: "",
  },
  {
    id: 4,
    name: "مريم يوسف الهاشمي",
    nationality: "إماراتية",
    phone: "+971 56 456 7890",
    email: "maryam@email.com",
    location: "أبوظبي",
    currentTitle: "مديرة موارد بشرية",
    experience: "12 سنة",
    lastEmployer: "مجموعة الإمارات",
    education: "ماجستير إدارة أعمال",
    university: "جامعة نيويورك أبوظبي",
    gpa: "3.9",
    skills: ["إدارة الموارد البشرية", "التوظيف", "SAP HR"],
    languages: ["عربي (لغة أم)", "إنجليزي (ممتاز)"],
    certifications: ["SHRM-CP", "CIPD Level 7"],
    aiSummary: "قيادية بارزة في مجال الموارد البشرية مع سجل حافل. تمتلك رؤية استراتيجية عالية.",
    status: "مقبول",
    rating: 5,
    date: "2025-04-21",
    companyId: 1,
    interviewDate: null,
    interviewTime: null,
    interviewNotes: "",
  },
];

export const DEMO_USERS = {
  "superadmin@smartcv.ae": {
    password: process.env.ADMIN_PASSWORD || "Admin@2024!",
    role: "superadmin",
    companyId: null,
    name: "Super Admin",
    companyName: null,
  },
  "admin@haad.ae": {
    password: process.env.COMPANY_ADMIN_PASSWORD || "Admin@2024!",
    role: "company_admin",
    companyId: "1",
    hrId: "demo-admin-1",
    name: "منى الشامسي",
    companyName: "هيئة أبوظبي للصحة",
    primaryColor: "#C9A84C",
  },
  "hr@company.ae": {
    password: process.env.HR_PASSWORD || "HR@2024!",
    role: "hr",
    companyId: "1",
    hrId: "demo-hr-1",
    name: "سارة المطيري",
    companyName: "هيئة أبوظبي للصحة",
    primaryColor: "#C9A84C",
  },
};
